#!/bin/bash
source config/.env
source lib/function.sh
source lib/function.sh
source lib/command/testconnection.sh


export ppwd=$(pwd)
if [[ -z "$1" ]]; then
    help
    exit 0
fi
for param in $@; do
	if [[ "$param" != "${param//-help/}" ]]; then
		help
		exit 0
	fi
	if [[ "$param" != "${param//-testconnection/}" ]]; then
		export connectiontest="true"
	fi
	if [[ "$param" != "${param//-verbose/}" ]]; then
		export verbose="true"
	fi
	if [[ "$param" != "${param//-copyonly/}" ]]; then
		export copyonly="true"
	fi
        if [[ "$param" != "${param//-checksetupfiles/}" ]]; then
                export checksetupfiles="true"
        fi
        if [[ "$param" != "${param//-installpackage/}" ]]; then
                export installpackage="true"
        fi
	if [[ "$param" != "${param//-showconfig/}" ]]; then
		cat setup.json |jq
	fi
done


if [[ "$connectiontest" == "true" ]]; then
	testconnection 
fi
